services:
  - docker

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - git

env:
  - QGIS_VERSION=bionic

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - ./scripts/ci/build-and-deploy.sh

sudo: false
