services:
  - docker

language: python

dist: trusty
sudo: false
cache:
  pip: true

python:
  - "3.6"

branches:
  except:
    - gh-pages

env:
  - QGIS_VERSION=bionic

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - ./scripts/ci/build-and-deploy.sh
