services:
  - docker

language: python

dist: trusty
sudo: false
cache:
  pip: true

python:
  - "3.6"

branches:
  except:
    - gh-pages

git:
  depth: 1

env:
  - QGIS_VERSION=bionic

script:
  - ./scripts/ci/build-and-deploy.sh
