name: build PyQGIS API docs

on:
  schedule:
    # runs every day
    - cron: '0 0 * * *'

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:
    # to manually trigger the build for a given branch
    # POST /repos/qgis/pyqgis/actions/workflows/2246440/dispatches
    inputs:
      qgis_branch:
        description: 'The QGIS branch'
        required: true
        default: 'master'
      home:
        description: 'location'
        required: false


jobs:
  build-docs:
    name: Build PyQGIS docs for ${{ github.event.inputs.qgis_branch || 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build PyQGIS docs
        env:
          QGIS_VERSION_BRANCH: ${{ github.event.inputs.qgis_branch || 'master' }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH: true
          RUNS_ON_CI: true
          BUILD_TESTING: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || false }}
        run: |
          echo "QGIS_VERSION_BRANCH: ${QGIS_VERSION_BRANCH}"
          echo "PUBLISH: ${PUBLISH}"
          echo "BUILD_TESTING: ${BUILD_TESTING}"
          ./scripts/run-docker.sh

